# Generated by Django 3.2.7 on 2021-10-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='Contry',
            field=models.EmailField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
